# - ros_topic_name: "/cmd_vel"
  # gz_topic_name: "/cmd_vel"
  # gz_type_name: "gz.msgs.Twist"
  # ros_type_name: "geometry_msgs/msg/Twist"
  # direction: BIDIRECTIONAL

# - ros_topic_name: "/odom"
  # gz_topic_name: "/odom"
  # gz_type_name: "gz.msgs.Odometry"
  # ros_type_name: "nav_msgs/msg/Odometry"
  # direction: BIDIRECTIONAL

# - ros_topic_name: "/tf"
  # gz_topic_name: "/tf"
  # gz_type_name: "gz.msgs.Pose_V"
  # ros_type_name: "tf2_msgs/msg/TFMessage"
  # direction: BIDIRECTIONAL

# - ros_topic_name: "/joint_states"
  # gz_topic_name: "/joint_states"
  # gz_type_name: "gz.msgs.Model"
  # ros_type_name: "sensor_msgs/msg/JointState"
  # direction: BIDIRECTIONAL

- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  gz_type_name: "gz.msgs.IMU"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: BIDIRECTIONAL

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS 

